kafka:
  bootstrap-servers: localhost:9092
  action-topic: stats.user-actions.v1
  similarity-topic: stats.events-similarity.v1
  auto-commit: false
  group-id: action-group

user-action:
  view: 0.4
  register: 0.8
  like: 1.0

logbook:
  format:
    style: http

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: TRACE